[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
ciborium = { workspace = true }
serde_json_any_key = "2.0.0"
serde_bytes = "0.11.14"
candid = { workspace = true }
ic-stable-structures = { workspace = true }
