[package]
name = "shared_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
ciborium = { workspace = true }
candid = { workspace = true }
ic-stable-structures = { workspace = true }
